```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
set.seed("1234")
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(countrycode))
suppressPackageStartupMessages(library(visdat))
suppressPackageStartupMessages(library(interactions))
suppressPackageStartupMessages(library(forestplot))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(xtable))
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(naivebayes))
suppressPackageStartupMessages(library(scales))
```

```{r read data}
odata <- read.csv("the_office.csv")
```

```{r Lineup 1}
office_samp1 <- odata %>%
  select(all_of(c("imdb_rating", "total_votes", "n_lines", "n_words")))

office_mod1 <- imdb_rating ~ total_votes + n_lines + n_words

office_fit1 <- lm(office_mod1, data = office_samp1)

aug_sampo1 <- augment(office_fit1)
lineup_resids_o1 <- lineup(null_lm(office_mod1, method = "boot"), true = aug_sampo1, n=9, pos=9)

lineup_resids_o1 %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  geom_point(shape = 1, alpha=0.8) +
  geom_smooth(col="red", method = "loess", se=FALSE, linewidth = 0.5) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 15, Residuals vs. Fitted",
        x ="Fitted values", y = "Residuals")
suppressMessages(ggsave("LUO1_RvF_wL.png", path = "Mock Lineups/Office Lineup 1 (pos9)"))

lineup_resids_o1 %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  geom_point(shape = 1, alpha=0.8) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 15, Residuals vs. Fitted",
        x ="Fitted values", y = "Residuals")
suppressMessages(ggsave("LUO1_RvF_woL.png", path = "Mock Lineups/Office Lineup 1 (pos9)"))



lineup_resids_o1 %>%
  group_by(.sample) %>%
  mutate(.std.resid_null = .resid/sd(.resid), 
         .scale_null = sqrt(abs(.std.resid_null))) %>%
  ggplot(aes(x = .fitted, y = .scale_null)) +
  geom_point(shape = 1, alpha=0.8, ) +
  geom_smooth(col="red", method = "loess", se=FALSE, linewidth = 0.5) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 15, Scale-Location",
        x ="Fitted values", y = TeX("$\\sqrt{|standardized\\,\\, residuals|}$"))
suppressMessages(ggsave("LUO1_SL_wL.png", path = "Mock Lineups/Office Lineup 1 (pos9)"))

lineup_resids_o1 %>%
  group_by(.sample) %>%
  mutate(.std.resid_null = .resid/sd(.resid), 
         .scale_null = sqrt(abs(.std.resid_null))) %>%
  ggplot(aes(x = .fitted, y = .scale_null)) +
  geom_point(shape = 1, alpha=0.8, ) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 15, Scale-Location",
        x ="Fitted values", y = TeX("$\\sqrt{|standardized\\,\\, residuals|}$"))
suppressMessages(ggsave("LUO1_SL_woL.png", path = "Mock Lineups/Office Lineup 1 (pos9)"))

```

```{r Lineup 2}
office_samp2 <- odata %>%
  select(all_of(c("imdb_rating", "total_votes", "n_lines", "n_words")))

office_mod2 <- imdb_rating ~ total_votes + n_lines

office_fit2 <- lm(office_mod2, data = office_samp2)

aug_sampo2 <- augment(office_fit1)
lineup_resids_o2 <- lineup(null_lm(office_mod1, method = "boot"), true = aug_sampo2, n=9, pos=5)

lineup_resids_o2 %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  geom_point(shape = 1, alpha=0.8) +
  geom_smooth(col="red", method = "loess", se=FALSE, linewidth = 0.5) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 16, Residuals vs. Fitted",
        x ="Fitted values", y = "Residuals")
suppressMessages(ggsave("LUO2_RvF_wL.png", path = "Mock Lineups/Office Lineup 2 (pos5)"))

lineup_resids_o2 %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  geom_point(shape = 1, alpha=0.8) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 16, Residuals vs. Fitted",
        x ="Fitted values", y = "Residuals")
suppressMessages(ggsave("LUO2_RvF_woL.png", path = "Mock Lineups/Office Lineup 2 (pos5)"))



lineup_resids_o2 %>%
  group_by(.sample) %>%
  mutate(.std.resid_null = .resid/sd(.resid), 
         .scale_null = sqrt(abs(.std.resid_null))) %>%
  ggplot(aes(x = .fitted, y = .scale_null)) +
  geom_point(shape = 1, alpha=0.8, ) +
  geom_smooth(col="red", method = "loess", se=FALSE, linewidth = 0.5) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 16, Scale-Location",
        x ="Fitted values", y = TeX("$\\sqrt{|standardized\\,\\, residuals|}$"))
suppressMessages(ggsave("LUO2_SL_wL.png", path = "Mock Lineups/Office Lineup 2 (pos5)"))

lineup_resids_o2 %>%
  group_by(.sample) %>%
  mutate(.std.resid_null = .resid/sd(.resid), 
         .scale_null = sqrt(abs(.std.resid_null))) %>%
  ggplot(aes(x = .fitted, y = .scale_null)) +
  geom_point(shape = 1, alpha=0.8, ) +
  facet_wrap(~ .sample) +
  labs(title="Lineup 16, Scale-Location",
        x ="Fitted values", y = TeX("$\\sqrt{|standardized\\,\\, residuals|}$"))
suppressMessages(ggsave("LUO2_SL_woL.png", path = "Mock Lineups/Office Lineup 2 (pos5)"))

```


```