```{r setup, echo=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("gridExtra"))
suppressPackageStartupMessages(library("visdat"))
suppressPackageStartupMessages(library("countrycode"))
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("knitr"))
suppressPackageStartupMessages(library("nullabor"))
suppressPackageStartupMessages(library("ggthemes"))
suppressPackageStartupMessages(library("broom"))
suppressPackageStartupMessages(library("latex2exp"))
suppressPackageStartupMessages(library("reshape2"))

```

```{r Load-data}
# Load and store data
load("easySHARE_data.rda")
data <- easySHARE_rel8_0_0
```

```{r fix-missing-data}
# Set missing values to NA       
data[data < 0] <- 0

# Replace country codes with country names
data$country_mod <- countrycode(factor(data$country_mod),
  origin = "iso3n",
  destination = "country.name"
)
```

```{r Set-lists}
# binary variables
factor_list <- c(
  "female", "dn004_mod",
  "partnerinhh", "mother_alive", "father_alive", "ever_smoked",
  "hc012_", "hc029_"
)

# variables with more than two levels
ordered_list <- c(
  "iv009_mod", "hhsize", "eurod",
  "ch001_", "chronic_mod", "adla", "br015_", "co007_",
  "br010_mod", "maxgrip", "sphus", "isced1997_r"
)

# continuous variables
nonfactor_list <- c("age", "country_mod")
```

```{r factor-levels}
# Factoring binary variables as dummy variables
for (column in factor_list) {
  if (column != "hc029_") {
    data[, column] <- ifelse(data[, column] == "1", 1, 0)
  } else {
    data$hc029_ <- ifelse(data[, column] == "5", 0, 1)
  }
  data[, column] <- factor(data[, column], levels = c(0, 1), labels = c("No", "Yes"))
}


# Factor non-binary variables
for (column in ordered_list) {
  data[, column] <- factor(data[, column])
}

# Simplifying levels for specific variables
levels(data$isced1997_r) <- list(
  "Secondary and Below" = as.character(0:3),
  "Post Secondary" = as.character(4:6),
  "Other" = as.character(95:96)
)

levels(data$eurod) <- list(
  "Not Depressed" = as.character(0:3),
  "Somewhat Depressed" = as.character(4:6),
  "Relatively Depressed" = as.character(7:9),
  "Very Depressed" = as.character(10:12)
)

levels(data$hhsize) <- list(
  "Up to 4" = as.character(1:4),
  "More than 4" = as.character(c(4:12, 14:15))
)


levels(data$iv009_mod) <- list(
  "City_sub" = as.character(1:2),
  "Town_rural" = as.character(3:5)
)

levels(data$sphus) <- list(
  "Good" = as.character(1:3),
  "Not Good" = as.character(4:5)
)

levels(data$ch001_) <- list(
  "Up to 2" = as.character(0:2),
  "More than 2" = as.character(3:19)
)

levels(data$chronic_mod) <- list(
  "0" = as.character(0),
  "1-3" = as.character(1:3),
  "4-10" = as.character(4:10)
)

levels(data$adla) <- list(
  "High Mobility" = as.character(0:2),
  "Low Mobility" = as.character(3:5)
)

levels(data$br015_) <- list(
  "Often" = as.character(1:2),
  "Rarely" = as.character(3:4)
)

levels(data$co007_) <- list(
  "With Difficulty" = as.character(1:2),
  "Relatively easily" = as.character(3:4)
)

levels(data$br010_mod) <- list(
  "Rarely" = as.character(1:2),
  "Occasionally" = as.character(3:4),
  "Regularly" = as.character(5:7)
)

levels(data$maxgrip) <- list(
  "Low" = as.character(1:35),
  "High" = as.character(36:99)
)
```

```{r setting-up-data}
factor_list2 <- c(
  "female", "dn004_mod",
  "partnerinhh", "ever_smoked",
  "hc012_", "hc029_"
)

# variables with more than two levels
ordered_list2 <- c(
  "iv009_mod", "hhsize", "eurod",
  "ch001_", "chronic_mod", "adla", "br015_", "co007_",
  "br010_mod", "maxgrip", "sphus", "isced1997_r"
)

# continuous variables
nonfactor_list2 <- c("age")

```

```{r cut data}
data$country_mod <- factor(data$country_mod)
data$wave <- factor(data$wave)

print(table(data$country_mod, data$wave)[,]) 
# print(summary(data$country_mod))

# Austria, Belgium, Denmark, France, Germany, Italy, Spain, Sweden, Switzerland
```

```{r}
final_data <- data %>%
  filter(wave %in% c(5)) %>%
  filter(country_mod %in% c("Austria", "Belgium", "Denmark", "France", "Germany", 
                            "Italy", "Spain", "Sweden", "Switzerland")) %>%
  select(all_of(c(factor_list, ordered_list, nonfactor_list)), "bmi")
```

```{r}
# summary(final_data)
```





```{r export dataset}

# save(final_data, file = "share_data.csv")

write.csv(final_data, "C:/Users/mayez/OneDrive - University of Edinburgh/Year 5/Dissertation/Code/mmath_dissertation/Shiny App/diag_plots/share_data.csv", row.names=FALSE)

```

